services:
  ralphee:
    image: osrf/ros:humble-desktop
    platform: linux/amd64
    volumes:
      - ./:/root/ralphee_ws
    working_dir: /root/ralphee_ws
    entrypoint: sleep infinity
volumes:
  ralphee-data:
