services:
  ralphee:
    image: osrf/ros:humble-desktop
    platform: linux/amd64
    volumes:
      - ./:~/haql-rover
      - ralphee-data:~
      - ros:/opt/ros
      - /private/tmp/com.apple.launchd.XWemurepAA:/private/tmp/com.apple.launchd.XWemurepAA:rw
    working_dir: ~/haql-rover
    entrypoint: sleep infinity
    environment:
      - USERNAME=default
      - WEBOTS_SHARED_FOLDER=~/ralphee_ws/src/webots_dev/worlds
    ports:
      - '3000:3000'
volumes:
  ralphee-data:
  ros:
