services:
  ralphee:
    image: osrf/ros:humble-desktop
    platform: linux/amd64
    volumes:
      - ./:/root/ralphee_ws
      - ralphee-data:/root
      - ros:/opt/ros
      - /private/tmp/com.apple.launchd.XWemurepAA:/private/tmp/com.apple.launchd.XWemurepAA:rw
    working_dir: /root/ralphee_ws
    entrypoint: sleep infinity
    environment:
      - USERNAME=default
      - WEBOTS_SHARED_FOLDER=~/ralphee_ws/src/webots_dev
    ports:
      - '3000:3000'
volumes:
  ralphee-data:
  ros:
