services:
  ralphee:
    image: ros:humble-ros-base
    volumes:
      - ./:/root/haql-rover
      - ralphee-data:/root
      - ros:/opt/ros
    working_dir: /root/haql-rover
    entrypoint: sleep infinity
    environment:
      - USERNAME=default
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=offscreen
      - WEBOTS_SHARED_FOLDER=/root/haql-rover/src/webots_dev/worlds
    ports:
      - '3000:3000'
      - '3001:3001'
      - '3002:3002'
volumes:
  ralphee-data:
  ros:
