services:
  ralphee:
    image: osrf/ros:humble-desktop
    platform: linux/amd64
    volumes:
      - ./:/root/ralphee_ws
      - ralphee-data:/root
      - ros:/opt/ros
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /root/ralphee_ws
    entrypoint: sleep infinity
    environment:
      - DISPLAY=docker.for.mac.host.internal:0
      - USERNAME=default
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=offscreen
      - WEBOTS_SHARED_FOLDER=~/ralphee_ws/src/webots_dev/worlds
    ports:
      - '3000:3000'
      - '3001:3001'
      - '3002:3002'
volumes:
  ralphee-data:
  ros:
